name: test-actions
on: [push, pull_request]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NO_COVERAGE_BADGE_UPDATE: 1
      FLAGS: FETCH_SERVICE_DISABLE,POST_CONFIGURE_TEST,WEB_PLATFORM_TESTS,CONTINUE_ON_ERROR,SPEC_BROWSER
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: denoland/setup-deno@v1
        with:
          deno-version: 'v1.x'
      - run: |
          yarn install
          yarn add --dev https://github.com/web-platform-tests/wpt.git
          npx playwright install-deps
      - run: yarn build
      # yarn coverage === c8 + yarn test
      - run: yarn coverage
      - run: yarn test:deno
